### ISSUE TITLE
essentiallysports.com

### ISSUE THREAD

**Issue by zzebrum** [AdguardTeam/DisableAMP#34]
@adguard-bot commented on [Sun Sep 20 2020](https://github.com/AdguardTeam/AdguardFilters/issues/64279)

### Issue URL (Incorrect Blocking)
 [https://www.essentiallysports.com/nba-news-miami-heat-rookie-tyler-herro-makes-history-as-he-joins-kobe-bryant-in-elite-playoff-record-basketball/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.essentiallysports.com%2Fnba-news-miami-heat-rookie-tyler-herro-makes-history-as-he-joins-kobe-bryant-in-elite-playoff-record-basketball%2F)
### Comment
Username: @jenabaivab
> Tried with multiple browsers. Used a browser with no https filtering, and it worked perfectly. Have been seeing this with a lot of news websites recently. Mostly sports websites, it's weird.
> --
> The information below is automatically generated. Do not delete it.
> 
> Custom userscripts:
> https://userscripts.adtidy.org/release/disable-amp/1.0/disable-amp.meta.js
> https://userscripts.adtidy.org/release/adguard-extra/1.0/adguard-extra.meta.js
> 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/jQabl82.jpg)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/c3rieYf.jpg)
</details>

### System configuration

Information | value
--- | ---
Platform: | Android 10
AdGuard product: | AdGuard for Android v4.0 nightly 2 (12)
Browser: | Chrome
AdGuard mode: | VPN
Filtering quality: | High-quality
HTTPS filtering: | enabled
DNS requests blocking: | enabled
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base, <br/>AdGuard Mobile Ads<br/><br/><b>Privacy:</b><br/> EasyPrivacy<br/><br/><b>Annoyances:</b><br/> Fanboy's Annoyances

**Comment by tvinzz** [comment]
fixed https://github.com/AdguardTeam/AdguardFilters/commit/71fc58d5344a16de2a3ac67c69d86cc98cd0e61a

**Comment by jenabaivab** [comment]
@tvinzz 

It's possible this is not happening due to the DisableAMP extension specifically, but it's not working still. The articles stay blank even if Adguard is turned off. This and thesportsrush articles from google news search.

**Comment by lolka4toli** [comment]
@tvinzz some users state it still broken – like on the first screenshot, without any text-content.

**Comment by jenabaivab** [comment]
It's due to the social media elements. I tried disabling fanboy's annoyances and used Adguard social media filter, same result. Works fine with both of them disabled.

**Comment by ameshkov** [comment]
@tvinzz plz take a look

**Comment by tvinzz** [comment]
@jenabaivab, is the problem still occurs?
DisableAMP userscript works fine for https://www.essentiallysports.com/ on my end.

**Comment by jellizaveta** [comment]
Unfortunately, I have not been able to reproduce this issue. It seems that resolved for now.
